# Generated by Django 4.2.7 on 2023-12-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=148)),
                ('Email', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
